# symfony-2.7\my_project_name\app\config\routing.yml
sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    # prefix:   /sdz/blog
    prefix:   /blog

tech_corp_front:
    resource: "@TechCorpFrontBundle/Resources/config/routing.yml"
    prefix:   /tech

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
